baseURL = "https://example.com"
languageCode = "en-US"
title = "Split - HTML Template Demo"
disableKinds = ["section", "taxonomy", "term", "rss", "sitemap"]

# Local preview mode
relativeURLs = true
uglyURLs = true

# Copyright
copyright = "&copy;2024 Your Name"

[params]
  # Metadata for search engines and social sharing
  author = "Jenny Jones"
  description = "Split is a centrally-divided layout for a professional online presence with a big image or video left with alongside content."
  shareImage = "images/social.jpg"
  twitterHandle = "onepagelove"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Header 1"

      [[params.links.list1.link]]
        text = "Link 1"
        url = "#"
        new_tab = true # new tab

      [[params.links.list1.link]]
        text = "Link 2"
        url = "#"
        new_tab = false # Default, open at same tab

      [[params.links.list1.link]]
        text = "Link 3"
        url = "#"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Header 2"

      [[params.links.list2.link]]
        text = "Link 1"
        url = "#"

      [[params.links.list2.link]]
        text = "Link 2"
        url = "#"

      [[params.links.list2.link]]
        text = "Link 3"
        url = "#"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Header 3"

      [[params.links.list3.link]]
        text = "Link One"
        url = "#"

      [[params.links.list3.link]]
        text = "Link Two"
        url = "#"

      [[params.links.list3.link]]
        text = "Link Three"
        url = "#"
