baseURL = "https://example.com"
languageCode = "en-US"
title = "Maliatopia"
disableKinds = ["section", "taxonomy", "term", "rss", "sitemap"]

# Local preview mode
relativeURLs = true
uglyURLs = true

# Copyright
copyright = "&copy;2024 Your Name"

[params]
  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/20240301_115128.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/Snapchat-64363206.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Study guides"

      [[params.links.list1.link]]
        text = "Studyflix"
        url = "https://studyflix.de/"
      [[params.links.list1.link]]
        text = "Serlo"
        url = "https://de.serlo.org/"

      [[params.links.list1.link]]
        text = "simpleclub"
        url = "https://simpleclub.com"
  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Baking recepies"

      [[params.links.list2.link]]
        text = "Thesaltedsweets"
        url = "https://thesaltedsweets.com/"

      [[params.links.list2.link]]
        text = "Cookiedoughdiary"
        url = "https://thecookiedoughdiaries.com/"

      [[params.links.list2.link]]
        text = "Chahinez_tbt"
        url = "https://lifestyleofafoodie.com/"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Social media"

      [[params.links.list3.link]]
        text = "Instagram"
        url = "https://www.instagram.com/maliadessu?igsh=MTR5bzVnZmlvOGJt"

      [[params.links.list3.link]]
        text = "Tiktok"
        url = "https://www.tiktok.com/@apparentlymalia?_t=8kHi2nNpdYG&_r=1"

      [[params.links.list3.link]]
        text = "Snapchat"
        url = "https://www.snapchat.com/add/maliakaefra?sender_web_id=d4be3758-7f00-4fd1-80a2-6e6df29d63cc&device_type=desktop&is_copy_url=true"
